fullshelf/fullshelf/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('shop/', include('shop.urls')),
    path('admin/', admin.site.urls),
]

fullshelf/shop/urls.py
from django.urls import path, re_path, include

from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'),
    #path('search_results', views.search_results, name='search_results'),
    path('product_page/<int:product_id>/', views.product_page, name='product_page'),
    #re_path(r'^search_results/(?P<page_number>\d+)/$', views.search_results, name='search_results'),
    path('search_results/<int:page_number>/',views.search_results, name='search_results'),

    path(r'^search/', include('haystack.urls')),
    
]

fullshelf/shop/models.py
from django.db import models
from django.contrib.postgres import fields

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=200)
    image_url = models.URLField(default='no-image')
    description = models.CharField(max_length=10000, default="")
    upc = models.CharField(max_length=100, default="")
    model_number = models.CharField(max_length=100, default="")
    listings = fields.JSONField(default=[])

    best_vendor = models.CharField(max_length=50, default="")
    best_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    best_url = models.URLField(max_length=500, default='no-url')


    #price = models.DecimalField(max_digits=10, decimal_places=2)
    #url = models.URLField(default='no-url')
    
    
class ProductCategory(models.Model):
    name = models.CharField(max_length=200)


class Vendor(models.Model):
    name = models.CharField(max_length=200)

fullshelf/shop/forms.py
from django import forms
from .models import ProductCategory

class SearchBar(forms.Form):
    query = forms.CharField(
        max_length=400,
        widget=forms.TextInput(attrs={'placeholder': 'Enter product name, model number, URL, etc'})
        )

class DisplayItems(forms.Form):
    items_per_page = forms.ChoiceField(
        widget = forms.Select(attrs={'onChange':'form.submit()'}),
        choices = [(25, 25), (50, 50), (100, 100)]
    )

    sort_items = forms.ChoiceField(
        widget=forms.Select(attrs={'onChange':'form.submit()'}),
        choices=[('relevant', 'Relevant'), ('price_ascending', 'Price-Low to high'), ('price_descending', 'Price-High to low')]
    )

class Filters(forms.Form):
    price_range = forms.ChoiceField(
        widget=forms.RadioSelect(),
        choices=[('0-20', '$0 to $20'), ('20-50', '$20 to $50'), ('50-100', '$50 to $100'), ('100-999999', '$100 and above')]
        )

class SearchForm(forms.Form):
    query = forms.CharField(label='search_query', max_length=400)
    filter_categories = forms.ChoiceField()

fullshelf/shop/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from .models import Product, ProductCategory, Vendor
from .forms import Filters, DisplayItems
from .helpers import search

def index(request):
    context = {
        'main_menu': ['Electronics', 'Home Goods', 'Fashion', 'Entertainment', 'Cosmetics'],
    }
    return render(request, 'shop/index.html', context)

def product_page(request, product_id):
    product = Product.objects.get(id=product_id)

    context = {
        'product': product,
    }

    return render(request, 'shop/product_page.html', context)
    

def search_results(request, page_number):
    pages_to_show = 9

    query = request.GET['query']
    #full_product_list = Product.objects.filter(name__icontains=query)
    full_product_list = search(query, Product.objects.all())
    vendor_list = Vendor.objects.all()

    price_range = request.GET['price_range']
    if price_range != 'all':
        div_idx = price_range.find('-')
        lowest_price = int(price_range[0:div_idx])
        highest_price = int(price_range[div_idx+1:])
        full_product_list = full_product_list.filter(best_price__gte=lowest_price, best_price__lte=highest_price)

    sort_order = request.GET['sort_items']
    if sort_order == 'price_ascending':
        full_product_list = full_product_list.order_by('best_price')
    elif sort_order == 'price_descending':
        full_product_list = full_product_list.order_by('-best_price')

    items_per_pages = int(request.GET['items_per_page'])
    num_pages = int(len(full_product_list) / items_per_pages)
    
    paginator = Paginator(full_product_list, items_per_pages)
    product_list = paginator.get_page(page_number)

    if page_number < (pages_to_show / 2):
        if num_pages < pages_to_show:
            page_number_list = range(1, num_pages + 1)
        else:
            page_number_list = range(1, pages_to_show + 1)
    else:
        if num_pages < (int(page_number + (pages_to_show / 2))):
            page_number_list = range(int(page_number - (pages_to_show / 2) + 1), num_pages + 1)
        else:
            page_number_list = range(int(page_number - (pages_to_show / 2) + 1), int(page_number + (pages_to_show / 2) + 1))

    context = {
        'query': query,
        'product_list': product_list,
        'vendor_list': vendor_list,
        'page_number_list': page_number_list,
        'current_page': page_number,
        'DisplayItems': DisplayItems(initial={'items_per_page': request.GET['items_per_page'], 'sort_items': request.GET['sort_items']}),
        'Filters': Filters(initial={'price_range': request.GET['price_range']})
    }

    return render(request, 'shop/search_results.html', context)

fullshelf/shop/templates/shop/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'shop/index.css' %}" />

<html>
    <head>
        <link rel="shortcut icon" href="{%  static 'shop/favicon.ico' %}">

        {% block page-title %}
        <title>Full Shelf</title>
        {% endblock %}
    </head>
    <body>

    <form method="get" action = "{% url 'shop:search_results' page_number=1 %}">
        
        <div id="login-bar">
            <ul>
                <li><a>Login or Signup</a></li>
                <li id="myaccount">My Account</li>
            </ul>
        </div>
        
        <div class="header">
            <div id="top">
                <div id="left">
                </div>
                <div id="middle">
                    <div class="search-container">
                        <div id="category-selector">
                            <select>
                                {% for category in categories %}
                                <option>{{ category }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div id="search-bar">
                            {{ SearchBar.query }}
                        </div>
                        <div id="search-button">
                            <button type="submit">Search</button>
                        </div>
                    </div>
                </div>
                <div id="right">
                    <button>
                    Advanced Search    
                    </button>
                </div>
            </div>
            <div id="bottom">
                <div id="bottom-nav">
                    <div>
                        <a href="{% url 'shop:index' %}">
                        <div id="nav-header">
                            <p>Home</p>
                        </div>
                        </a>
                    </div>
                    <div id="categories">
                        <div id="nav-header">
                            <p>Categories</p>
                        </div>
                        <div id="submenu">
                            {% for key, value in header_categories.items %}
                            <div>
                                <ul>
                                    <li><b>{{ key }}</b></li>
                                    {% for i in value %}
                                    <li><a href='#'>{{ i }}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                            {% endfor %}
                        </div>
                        
                    </div>
                    <div id="deals">
                        <div id="nav-header">
                            <p>Deals</p>
                        </div>
                        <div id="submenu">
                            <div></div>
                            <div></div>
                            <div></div>
                            <div></div>
                        </div>
                    </div>
                    <div id="tools-menu">
                        <div id="nav-header">
                            <p>Tools</p>
                        </div>
                        <div id="submenu">
                            <div>
                                <div id="image"></div>
                                <div id="info">
                                    <h4>Comparison Tool</h4>
                                    <p>Loren Ipsum Loren Ipsum Loren Ipsum Loren Ipsum </p>
                                </div>
                            </div>
                            <div>
                                <div id="image"></div>
                                <div id="info"></div>
                            </div>
                            <div>
                                <div id="image"></div>
                                <div id="info"></div>
                            </div>
                            <div>
                                <div id="image"></div>
                                <div id="info"></div>
                            </div>
                            <div>
                                <div id="image"></div>
                                <div id="info"></div>
                            </div>
                        </div>
                    </div>
                </div>

                <div id="tools">
                    <div id="tools-header">
                        <p>My Watchlist</p>
                    </div>
                    <div id="watchlist">
                        <div></div>
                        <div>
                            <p>Product Title</p>
                            <p>Latest Price: $9.99</p>
                        </div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                    </div>
                </div>
            </div>
            
        </div>
        <!--<a href="{% url 'shop:index' %}"><img id="logo" src="{% static 'shop/icon.png' %}"></a>-->
        {% block main-content %}

        <input type="hidden" name="sort_order" value="relevance" />
        <input type="hidden" name="items_per_page" value=25 />
        <input type="hidden" name="sort_items" value="relevance" />
        <input type="hidden" name="price_range" value="all" />

        <!--
        <div id="header-nav">
            <ul>
                {% for nav in main_menu %}
                <li>
                    <div>
                        <p>{{ nav }}</p>
                        <div></div>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
        -->
        <main>
            <div id="description">
                <h1>Welcome to FullShelf,</h1>
                <h3>a search engine for shoppers, allowing you to compare products from all the internet's retailers</h3>
            </div>
        </main>


        {% endblock %}

        <footer>
            <div>
                <ul>
                    <li><b>About Us</b></li>
                    <li>Our Mission</li>
                    <li>Company History</li>
                    <li>FAQ</li>
                    <li>People</li>
                </ul>
            </div>
            <div>
                <ul>
                    <li><b>Contact</b></li>
                    <li>Contact Information</li>
                    <li>Help Center</li>
                    <li>Site Feedback</li>
                </ul>
            </div>
            <div>
                <ul>
                    <li><b>Partners</b></li>
                    <li>Add Your Products</li>
                </ul>
            </div>
        </footer>
    </form>

    <script src="{% static 'shop/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'shop/index.js' %}"></script>
    {% block scripts %}
    
    {% endblock %}

    </body>
</html>

fullshelf/shop/templates/shop/product_page.html
{% extends "shop/index.html" %}
{% load static %}

{% block page-title %}
<title>{{ product.name }}</title>
{% endblock %}

{% block main-content %}

<link rel="stylesheet" type="text/css" href="{% static 'shop/product_page.css' %}" />

<input type="hidden" name="items_per_page" value=25 />
<input type="hidden" name="sort_items" value="relevance" />
<input type="hidden" name="price_range" value="all" />

<div id="screen"></div>


<div class="container">

    <div id="product-header">

        <a href=#><p>Level 1 Category</p></a>
        <p>></p>
        <a href=#><p>Level 2 Category</p></a>
        <p>></p>
        <a href=#><p>Level 3 Category</p></a>

    </div>

    <div id="product-box">

        <div id="image-gallery">
            <div id="product-img"><img src={{ product.image_url }}></div>
            <div id="gallery-thumbs">
                <div><img src={{ product.image_url }}></div>
            </div>
        </div>
        
    
        <div id="product-description">
            <h2>{{ product.name }}</h2>
            <div id="rating">
                <ul>
                    <li id="starred"></li>
                    <li id="starred"></li>
                    <li id="starred"></li>
                    <li id="starred"></li>
                    <li></li>
                </ul>
                <a href="#reviews">See all reviews</a>
            </div>
            
            <div id="buy-box-wrapper">
                <div id="buy-box">
                    <p id="header">Best Price:</p>
                    <div id="buy">
                        <p id="price">${{ product.best_price }}</p>
                        
                        <div id="buynow">
                            <a target="_blank" href="{{ product.best_url }}"><button type="button">Buy now</button></a>
                        </div>

                        <div id="cheaper">
                            <button type="button">Show Cheaper Options</button>
                        </div>
                    </div>
                    <p id="vendor">From {{ product.best_vendor }}</p>
                </div>

                <div id="extra-box">
                    <div id="wishlist">
                        <img src="{% static 'shop/icons/file-text.svg' %}">
                        <a href="#"><p>Add to Watch List</p></a>
                    </div>
                    <div id="wishlist">
                        <img src="{% static 'shop/icons/shopping-bag.svg' %}">
                        <a href="#"><p>Notify me when price decreases</p></a>
                    </div>
                </div>
                
            </div>

            <div id="cheaper-options-wrapper">
                <div id="cheaper-options">
                    <button type="button"><img src="{% static 'shop/icons/chevron-left.svg' %}"></button>
                    <div id="product-gallery">
                        <div>
                            <div><img></div>
                            <p>$3.99</p>
                        </div>
                        <div>
                            <div><img></div>
                            <p>$30.99</p>
                        </div>
                        <div>
                            <div><img></div>
                            <p>$300.99</p>
                        </div>
                        <div>
                            <div><img></div>
                            <p>$3000.99</p>
                        </div>
                        <div>
                            <div><img></div>
                            <p>Price</p>
                        </div>
                    </div>
                    <button type="button"><img src="{% static 'shop/icons/chevron-right.svg' %}"></button>
                </div>
            </div>

            <div id="other-stores">
                <p id="one-p">More Stores:</p>
                <table cellspacing="0" id="other-stores-table">
                    <tr id="header">
                        <th>Store</th>
                        <th>Base price</th>
                        <th>Final price</th>
                        <th>Showing 1 of {{ product.listings|length }}</th>
                    </tr>
                    {% for listing in product.listings %}
                    {% if forloop.counter0 < 4 %}
                    <tr>
                        <td>{{ listing.vendor }}</td>
                        <td>${{ listing.price }}</td>
                        <td>${{ listing.price }}</td>
                        <td><a target="_blank" href="{{ listing.url }}"><button type="button">BUY</button></a></td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                </table>
                <p id="two-p">See all stores</p>
                <!--<p style="font-size:14px">Showing 1 of {{ product.listings|length }}</p>-->
            </div>
        </div>
        
    </div>

    <div id="product-details">
        <h2>Product Information</h2>
        <div id="table">
            <h4>Details</h4>
            <table cellspacing="0">
                <tr id="first">
                    <td>Brand</td>
                    <td>SkullCandy</td>
                </tr>
                <tr>
                    <td>Category</td>
                    <td>Electronics > Audio > Headphones</td>
                </tr>
                <tr>
                    <td>UPC</td>
                    <td>{{ product.upc }}</td>
                </tr>
                <tr>
                    <td>Model Number</td>
                    <td>{{ product.model_number }}</td>
                </tr>
                <tr>
                    <td>Dimensions</td>
                    <td>.</td>
                </tr>
                <tr>
                    <td>Weight</td>
                    <td>.</td>
                </tr>
            </table>
        </div>
        <div id="description">
            <h4>Description</h4>
            <p>{{ product.description }}</p>
        </div>
    </div>

    <div id="similiar-products">
        <h2 class="section-heading">Shop Similiar Products</h2>
        <ul>
            <li><div></div></li>
            <li><div></div></li>
            <li><div></div></li>
            <li><div></div></li>
            <li><div></div></li>
            <li><div></div></li>
            <li><div></div></li>
        </ul>
    </div>

    <div id="reviews"> 
        <h2 class="section-heading">Customer Reviews</h2>
    </div>

        
</div>

<!--
<script src="{% static 'shop/tablesort.js' %}"></script>
<script src="{% static 'shop/tablesort.number.js' %}"></script>
<script>
    new Tablesort(document.getElementById('other-stores-table'));
</script>
-->

{% endblock %}


{% block scripts %}
<script src="{% static 'shop/product_page.js' %}"></script>
{% endblock %}

fullshelf/shop/templates/shop/search_results.html
{% extends "shop/index.html" %}
{% load static %}

{% block page-title %}
<title>Search Results: {{ query }}</title>
{% endblock %}

{% block main-content %}

<link rel="stylesheet" type="text/css" href="{% static 'shop/style2.css' %}" />

<div class="container">

    <div class="search-sidebar">
        <div id="filter-top">
            <input id="filter-button" type="submit" value="Apply filters">
        </div>
        <div id="filter-list">
            <h4 class="filter-title">Category</h4>
            {% for category in categories %}
            <label>
                <input id="your_name" type="checkbox" name={{ category.name }}>
                <label for="your_name">{{ category.name }}</label>
            </label><br>
            {% endfor %}    

            <h4 class="filter-title">Vendor</h4>
            {% for vendor in vendor_list %}
            <label>
                <input type="checkbox" name={{ vendor.name }}>
                {{ vendor.name }}
            </label><br>
            {% endfor %} 

            <input type="hidden" name="price_range" value="all" />
            <h4 class="filter-title">Price</h4>
            {{ Filters.price_range }}
        </div>
    </div>

    <div class="search-results">
        <h3 id="showing">Showing search results for <i>{{ query }}</i></h3>
        
        <div class="results-header">
            <div class="results-options" id="show-per-page">
                <p><b>Items per page</b></p>
                {{ DisplayItems.items_per_page }}
            </div>
            <div class="results-options" id="sort-options">
                <p><b>Sort by</b></p>
                {{ DisplayItems.sort_items }}
            </div>
        </div>

        <div class="product-grid">
            {% for product in product_list %}
            <div class="product-container"> 
                <a href="{% url 'shop:product_page' product_id=product.id %}"><img src={{ product.image_url }} class="product-image"></a>
                <div class="product-description">
                    <p class="price"><b>${{ product.best_price }}</b> | {{ product.best_vendor }}</p>
                    <p class="title">{{ product.name|truncatechars:50}}</p>
                    <p class="title-full">{{ product.name }}</p>
                </div>
            </div>

            <div class="product-container-list">
                <img src={{ product.image_url }} class="product-image">
                <div>
                    <p>{{ product.name}}</p>
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="page-selector">
            <ul>
                <li id="arrow-select">
                    <button type="submit" formaction = "{% url 'shop:search_results' page_number=current_page|add:"-1" %}">
                            <img src="{% static 'shop/icons/chevron-left.svg' %}">
                    </button>
                </li>
                {% for page_number in page_number_list %}
                <li id="pg-num">
                    {% if page_number != current_page %}
                    <button type="submit" formaction = "{% url 'shop:search_results' page_number=page_number %}">{{ page_number }}</button>
                    {% else %}
                    <button style="background-color: #ba5b5b" type="submit" formaction = "{% url 'shop:search_results' page_number=page_number %}">{{ page_number }}</button>
                    {% endif %}
                </li>
                {% endfor %}
                <li id="arrow-select">
                    <button type="submit" formaction = "{% url 'shop:search_results' page_number=current_page|add:"1" %}">
                        <img src="{% static 'shop/icons/chevron-right.svg' %}">
                    </button>
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

fullshelf/shop/templates/shop/search_results_list.html
{% extends "shop/search_results.html" %}

{% block product-content %}
<div class="product-list">
    {% for product in product_list %}
    <div class="product-container"> 
        <img src={{ product.image_url }} class="product-image">
        <div class="product-description">
            <p class="price"><b>${{ product.price }}</b></p>
            <p class="title">{{ product.name|truncatechars:40}}</p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}